### ISSUE TITLE
Lighter Alternative to Express

### ISSUE THREAD

**Issue by vipulbhj** [fxnoob/delete-sensitive-history#4]
Can you please consider talking a look at https://github.com/vipulbhj/not-really-a-framework.

This might be a possible use case for this repo

**Comment by fxnoob** [comment]
yes.

**Comment by fxnoob** [comment]
for server side apis

**Comment by vipulbhj** [comment]
Should I port it then and remove the express layer ??

**Comment by fxnoob** [comment]
yes. fork the repository.

**Comment by vipulbhj** [comment]
Sure, I will submit a PR in a while

**Comment by fxnoob** [comment]
@vipulbhj  we need to implement or find a api to test whether a given url contains pornographic content.

**Comment by vipulbhj** [comment]
Okay, I will try to find one, or come up with someway it can be done

**Comment by vipulbhj** [comment]
Proposal for implementing this issue. 
Using the data available https://www.scribd.com/doc/273372736/2015-07-31-DoT-Block-Order-Decency
this is a list of all the sides banned by Indian gov during the 2015 porn ban.
I can create a new module that loads assets of words from a resource file. Store it in a JS object as keys and values being true(The idea is to store things as hashes, that thus reduce the access time using the inbuild hash function).

And export public method which will tell whether the url is porn or not

All the above computation will be done on the domain name only.

If this sounds right, please confirm so that I can proceed forth
