### ISSUE TITLE
chrome.tabs.onActivated.addListener( function(info) {     var tabId    = info.tabId,         windowId = info.windowId; }); chrome.tabs.onActiveChanged.addListener( function(tabId, info) {     tabId        = tabId;         // For comparison     var windowId = info.windowId; });

### ISSUE THREAD

**Issue by sainihitesh** [fxnoob/delete-sensitive-history#8]
chrome.tabs.onActivated.addListener( function(info) {
    var tabId    = info.tabId,
        windowId = info.windowId;
});
chrome.tabs.onActiveChanged.addListener( function(tabId, info) {
    tabId        = tabId;         // For comparison
    var windowId = info.windowId;
});

**Comment by fxnoob** [comment]
done
